# Project Euler : Problem 1
# Author: Bruce Hart <bruce.hart@gmail.com>

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import time

def euler2():
    fib = [1,2]

    while((fib[-1]+fib[-2]) <= 4000000):
        fib.append(fib[-1]+fib[-2])

    print sum(filter(lambda x: (x%2)==0,fib))

if __name__ == '__main__':
    time.clock()
    euler2()
    print "Executed in {} sec".format(time.clock())