# Project Euler: Problem 2
# Author: Bruce Hart <bruce.hart@gmail.com>

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def euler2():
    fib = [1, 2]
    
    # Extend the Fibonacci sequence up to the limit of four million
    while (fib[-1] + fib[-2]) <= 4000000:
        fib.append(fib[-1] + fib[-2])
    
    # Calculate the sum of even Fibonacci numbers
    even_sum = sum(x for x in fib if x % 2 == 0)
    print(even_sum)

if __name__ == '__main__':
    euler2()
