#Author: Bruce Hart <bruce.hart@gmail.com>

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


import time

def euler45():
    P = map(lambda n: n*(3*n-1)/2,xrange(1,100000))
    H = map(lambda n: n*(2*n-1),xrange(1,100000))
    
    d = 286
    
    while True:
        T = d*(d+1)/2
        if (T in P and T in H):
            print T
            return
        else:
            print d
            d+=1
    
     
    

if __name__ == '__main__':
    time.clock()
    euler45()
    print "Executed in {0} sec".format(time.clock())