#Author: Bruce Hart <bruce.hart@gmail.com>

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	    T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	P_n=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	H_n=n(2n-1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


import time

def triangle(n): return n*(n+1)/2
def pentagon(n): return n*((3*n)-1)/2
def hexagon(n): return n*((2*n)-1)

def euler45():
    t = 286
    p = 165
    h = 143

    while True:
        Tc = triangle(t)
        Pc = pentagon(p)
        Hc = hexagon(h)

        while(Pc < Tc):
            p += 1
            Pc = pentagon(p)

        while(Hc < Tc):
            h += 1
            Hc = hexagon(h)

        if (Pc == Tc and Hc == Tc):
            print Tc
            return

        t+=1

     
    

if __name__ == '__main__':
    time.clock()
    euler45()
    print "Executed in {0} sec".format(time.clock())